#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"


echo "===\n>> 检查分支名称..."

# Check if branch protection is enabled
if [[ -z $SKIP_BRANCH_PROTECTION ]]; then
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    PROTECTED_BRANCHES="^(main|master|pre)"

    if [[ $BRANCH =~ $PROTECTED_BRANCHES ]]; then
        echo ">> 当前分支 $BRANCH 仅允许合并,不允许直接提交修改."
        exit 1
    fi
else
    echo ">> 跳过分支保护."
fi

echo ">> 分支名称: OK"

npx lint-staged